name: Testing Workflow Concurrency
on:
  push:
    branches:
      - testingConcurrency

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: false

jobs:

 # Sync Commandsss
#   wait-for-workflows:
#     if: github.ref_name == 'testingConcurrency'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ahmadnassri/action-workflow-queue@v1

      # only runs additional steps if there is no other instance of `my-workflow.yml` currently runningsss
  timer-wait:
    if: github.ref_name == 'testingConcurrency'
    runs-on: ubuntu-latest
    steps:
      - name: Wait 1 minutes for attachment to complete
        uses: jakejarvis/wait-action@master
        with:
          time: '1m'

slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: 
      - timer-wait
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Work Flow Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-notifications
          SLACK_ICON: 'https://user-images.githubusercontent.com/98909645/173383354-c303d398-d64a-49ff-b796-261a54e92f1e.png'
          SLACK_COLOR: ${{ job.status }} 
          SLACK_USERNAME: Ray
          SLACK_TITLE: Deloyment
          SLACK_MESSAGE: ":red_circle: ${{needs.timer-wait.status}} :red_circle:"



