name: Testing Slack Notify
on:
  push:
    branches:
      - notifyslack

jobs:
# Waits for presetm timea
  timer-wait:
    name: Install NGINX
    if: github.ref_name == 'notifyslack'
    runs-on: ubuntu-latest
    steps:
      - name: Get Host
        id: get-host
        run: |
           echo "test"
           echo "jobName=Get Host" >> $GITHUB_OUTPUT
           exit 1 
           
      - name: SSH
        id: ssh-install
        run: |
           echo "test"
           echo "${{steps.Test.name}}"
           echo "jobName=ssh-install" >> $GITHUB_OUTPUT

      - name: Check Status
        run: |
          echo "${{steps.ssh-install.outputs.jobName}} has outcome: ${{steps.ssh-install.outcome}} "
          echo "${{steps.get-host.outputs.jobName}} has outcome: ${{steps.get-host.outcome}} "

  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - timer-wait
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Work Flow Failed
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_CHANNEL: github-notifications
  #         SLACK_ICON: 'https://user-images.githubusercontent.com/98909645/173383354-c303d398-d64a-49ff-b796-261a54e92f1e.png'
  #         SLACK_COLOR: ${{ job.status }} 
  #         SLACK_USERNAME: Ray
  #         SLACK_TITLE: ${{ needs.timer-wait.outputs.build_id }}
  #         SLACK_MESSAGE: "${{needs.timer-wait.result}}"



