name: Testing Workflow Concurrency
on:
  push:
    branches:
      - testingConcurrency
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"

jobs:
# Waits for presetm time
  timer-wait:
    if: github.ref_name == 'testingConcurrency'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          command_timeout: 120m
          host: ec2-13-57-17-208.us-west-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script_stop: false
          script: |
            INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
            pwd
            for i in {1..6}; do
              GH_INSTALL_APP="`wget -qO- http://169.254.169.254/latest/meta-data/tags/instance/GHINSTALL`"
              if [ "$GH_INSTALL_APP" = "true" ]
              then
                echo "Tag Updated"
              fi
              echo "tag value: $GH_INSTALL_APP"
              sleep 7
            done 
  
# aws ec2 create-tags --resources $INSTANCE_ID --region us-east-1 --tags Key=GHInstallApp,Value=false
  # slackNotification:
  #   name: Slack Notificationss
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - timer-wait
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Work Flow Failed
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_CHANNEL: github-notifications
  #         SLACK_ICON: 'https://user-images.githubusercontent.com/98909645/173383354-c303d398-d64a-49ff-b796-261a54e92f1e.png'
  #         SLACK_COLOR: ${{ job.status }} 
  #         SLACK_USERNAME: Ray
  #         SLACK_TITLE: ${{ needs.timer-wait.outputs.build_id }}
  #         SLACK_MESSAGE: "${{needs.timer-wait.result}}"



