name: Testing Slack Notify
on:
  push:
    branches:
      - notifyslack

jobs:
# Waits for presetm timea
  timer-wait:
    name: Timer wait
    if: github.ref_name == 'notifyslack'
    runs-on: ubuntu-latest
    steps:
      - name: Tes
        run: echo "test"
  status:
    needs:
      - timer-wait
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo "${{ toJson(needs.timer-wait) }}"
          echo "${{ needs}}"
          echo "${{ needs.timer-wait.result}}"

  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   needs: 
  #     - timer-wait
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Work Flow Failed
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_CHANNEL: github-notifications
  #         SLACK_ICON: 'https://user-images.githubusercontent.com/98909645/173383354-c303d398-d64a-49ff-b796-261a54e92f1e.png'
  #         SLACK_COLOR: ${{ job.status }} 
  #         SLACK_USERNAME: Ray
  #         SLACK_TITLE: ${{ needs.timer-wait.outputs.build_id }}
  #         SLACK_MESSAGE: "${{needs.timer-wait.result}}"



