name: Print Branch
on: 
  push:
    branches:
      - feature1 
      - feature2 
      - feature3
jobs:
  refresh-autoscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Feautre 1
        if: ${{github.ref}} == refs/heads/feature1
        run: echo "Feature 1"
      - name: Feature 2
        if: ${{github.ref}} == refs/heads/feature2
        run: echo "Feature 2"
      - name: Feature 3
        if: ${{github.ref}} == refs/heads/feature3
        run: echo "Feature3"
