name: Print Branch
on: 
  push:
    branches:
      - feature1 
      - feature2 
      - feature3
jobs:
  refresh-autoscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli          
  feature1-test:
    runs-on: ubuntu-latest
    needs: refresh-autoscale
    if: github.ref_name == 'feature1'
    steps:
      - name: Feature 1
        run: echo "Inside feature1 branch"
  feature2-test:
    runs-on: ubuntu-latest
    needs: refresh-autoscale
    if: github.ref_name == 'feature2'
    steps:
      - name: Feature 2
        run: echo "Inside feature2 branch"
  feature3-test:
    runs-on: ubuntu-latest
    needs: refresh-autoscale
    if: github.ref_name == 'feature3'
    steps:
      - name: Feature 3
        run: echo "Inside feature3 branch"
