name: Refresh Instance
on: 
  push:
    branches:
      -main
jobs:
  refresh-autoscale:
    runs-on: ubuntu-latest
    steps:
    - name: ASG instance-refresh
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: autoscaling start-instance-refresh --auto-scaling-group-name tribehealth-platform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
  
  
