name: Refresh Instance
on: 
  workflow_run:
    workflows: ["Python Application"]
    types:
      - completed
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-2"
  
jobs:
  aws-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
  main-refresh:
      runs-on: ubuntu-latest
      needs: aws-cli
      if: ${{ github.ref_name == 'main') && (github.event.workflow_run.conclusion == 'success') }}
      steps:
        - name: Refresh Main Instance
          run: aws autoscaling start-instance-refresh --auto-scaling-group-name tribehealth-platform          

  stage-refresh:
      runs-on: ubuntu-latest
      needs: aws-cli
      if: ${{ github.ref_name == 'stage') && (github.event.workflow_run.conclusion == 'success') }}
      steps:
        - name: Refresh Stage Instance
          run: aws autoscaling start-instance-refresh --auto-scaling-group-name 'ASGGROUPNAME'          

  dev-refresh:
    runs-on: ubuntu-latest
    needs: aws-cli
    if: ${{ github.ref_name == 'dev') && (github.event.workflow_run.conclusion == 'success') }}
    steps:
      - name: Refresh Dev Instance
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name 'ASGGROUPNAME'          

