# name: ASG LoadBalancer
# on:
#   push:
#     branches:
#       - main
# Testing triggers
name: Test release on no changes to Directories
on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            migrations:
              - 'testingTriggers/**'
      
      - name: Check changes
        if: steps.filter.outputs.migrations == 'true'
        run: exit 0

  # JOB to build and test backend code
  release:
    needs: changes
    if: ${{ needs.changes.outputs.migrations == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"