# Check github event
  # If workflow call:
    # Check what branch it is from the tag
    # Rollback that environment
  # If release deletion:
    # run rollback on main
  
name: Rollback
on:
  workflow_call:
  release:
    types: 
      - deleted
# TODO: 
# - Check to see if you can run jobs depending on trigger event
jobs:
# Get the latest Tag's branch and store into variable 
  get-branch:
    runs-on: ubuntu-latest
    outputs: 
      bName: ${{steps.branch-name.outputs.branchN}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Branch From Tag
        id: branch-name
        run: |
          tag=${{github.ref_name}}
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo "branchN=$branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch"
          tagStripped=${tag/v1\/}
          echo "Tag is $tag"
          echo "Tag Stripped is $tagStripped"
          echo "Event that triggered it is ${{github.event_name}}"