# Will run remote tests
# Check github event name and run based on that
# Tests Failed:
  # If it is a stage or Dev tag
    # get ssm and call deploy workflow with the latest tag as input
  # if release:
    # delete the previous release




# If tests are a success - update last working commit on param store
# Else
  # Grab the latest commit from param store
  # Call workflow again
  # Refresh with this last working commit 
# _______________________________________________________________________
name: Run Tests
on:
  workflow_call:

jobs:
  get-latest-stable-commit:
    runs-on: ubuntu-latest
    outputs:
      last-commit: ${{steps.parameter.outputs.value}}
    steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: 'Get value from Parameter Store'
      id: parameter
      uses: poad/get-aws-ssm-parameter@v1.0.0
      with: 
        parameter-name: /stableCommit
        aws-region: us-west-1
  
    - name: 'Another example step'
      run: echo ${{ steps.parameter.outputs.value }}

  rollback-environment:
    needs: get-latest-stable-commit
    uses: rayala3314/aws-autoscale/.github/workflows/rollback.yml@main
    with:
      commit-hash: ${{ needs.get-latest-commit.outputs.last-commit }}

