name: Sync S3 Bucket
on:
  workflow_call:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"

jobs:
# AWS CLI
  aws-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
  


# Sync Commands
  sync-bucket:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    outputs:
      folderName: ${{steps.check-directory-existence.outputs.oFolderName}}
    name: Sync Dev Bucket to Stage Bucket
    needs:
      - aws-cli
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Check if Directory in Stage
      id: check-directory-existence
      run: |
        objectFolderName=$(aws s3api list-objects-v2 --bucket dev-test-eagles --query 'sort_by(Contents, &LastModified)[-1].Key' | tr -d '"' | grep -oE '[^\"].*\/\s*')
        echo "$objectFolderName"
        echo "oFolderName=$objectFolderName" >> $GITHUB_OUTPUT
        echo "subDirectoryName=$objectFolderName" >> $GITHUB_OUTPUT
        PREFIXCHECK=$(aws s3api list-objects-v2 --bucket stage-tests-eagles --prefix "$objectFolderName" --query "Contents[0].Key" --output text)
        existence=''
        if [ $PREFIXCHECK == 'None' ]
        then
          existence='false'
        else
          existence='true'
        fi
        echo "existenceDirectory=$existence" >> $GITHUB_OUTPUT


    - name: Create Copy and Sync in Stage
      if: contains(steps.check-directory-existence.outputs.existenceDirectory, 'true')
      run: |
        aws s3 cp --recursive s3://stage-tests-eagles/${{steps.check-directory-existence.outputs.oFolderName}} s3://stage-tests-eagles/backup-${{steps.check-directory-existence.outputs.oFolderName}}
        aws s3 cp --recursive s3://dev-test-eagles/${{steps.check-directory-existence.outputs.oFolderName}} s3://stage-tests-eagles/${{steps.check-directory-existence.outputs.oFolderName}}

    - name: Create copy if it doesn't exist
      if: contains(steps.check-directory-existence.outputs.existenceDirectory, 'false')
      run: aws s3 cp --recursive s3://dev-test-eagles/${{steps.check-directory-existence.outputs.oFolderName}} s3://stage-tests-eagles/${{steps.check-directory-existence.outputs.oFolderName}}

  debug:
    runs-on: ubuntu-latest
    needs: sync-bucket
    steps:
      - name: Debug Output Two
        id: stepTwo
        run: echo "${{ toJson(needs.sync-bucket) }}"
      # In case of rollback sync back to old-backups with this command
      # aws s3 cp --recursive s3://tribehealth-backups-stage/old-${{steps.check-directory-existence.outputs.oFolderName}} s3://tribehealth-backups-stage/${{steps.check-directory-existence.outputs.oFolderName}}
          


