name: Second YAML
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed


jobs:
  second:
    runs-on: ubuntu-latest

  if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: Echo Second
        run: |
          echo "Second YAML File"
          echo "test"