name: Deploy
on:
  push:
    branches:
      - main     # Production
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"

jobs:
# Run Internal Remote tests
  aws-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
  create-snapshot:
    if: github.ref_name == 'main'
    needs: aws-cli
    name: Snapshot of blue db
    runs-on: ubuntu-latest
    steps:
    - name: Blue Snapshot
      run: |
        DBSnap_ID=$(aws rds create-db-snapshot --db-instance-identifier gh-blue-database --db-snapshot-identifier test291ghsnapshot --query "DBSnapshot.DBSnapshotIdentifier" --output text)
        echo "DBSNAP_ID=$DBSnap_ID" >> $GITHUB_ENV
    - run:
        echo "${{env.DBSNAP_ID}}"
  restore-from-snapshot:
    if: github.ref_name == 'main'
    needs: [aws-cli, create-snapshot]
    name: Restore from blue
    runs-on: ubuntu-latest
    steps:
    - name: Restoring from blue
      run: aws rds restore-db-instance-from-db-snapshot --db-instance-identifier green-db --db-snapshot-identifier ${{env.DBSNAP_ID}}
