name: Deploy
on:
  push:
    branches:
      - main     # Production
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"

jobs:
# Run Internal Remote tests
  aws-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli


# Create Snapshot of Blue database
        # DBSnap_ID=$(aws rds create-db-snapshot --db-instance-identifier gh-blue-database --db-snapshot-identifier test291ghsnapshot --query "DBSnapshot.DBSnapshotIdentifier" --output text)
        # echo "DBSNAP_ID=$DBSnap_ID" >> $GITHUB_ENV

  create-snapshot:
    if: github.ref_name == 'main'
    needs: aws-cli
    outputs:
      snapshotIdentifier: ${{steps.blue-db-snapshot.outputs.DBSnapshot}}
    name: Snapshot of Blue db
    runs-on: ubuntu-latest
    steps:
    - name: Blue Snapshot
      id: blue-db-snapshot
      run: |
        DBSnap_ID=$(aws rds create-db-snapshot --db-instance-identifier gh-blue-database --db-snapshot-identifier test1191ghsnapshot --query "DBSnapshot.DBSnapshotIdentifier" --output text)
        echo "DBSnapshot=$DBSnap_ID" >> $GITHUB_OUTPUT
  debug:
    needs: [create-snapshot]
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo "${{ toJson(needs.create-snapshot) }}"


# Restoring From given snapshot
  restore-from-snapshot:
    if: github.ref_name == 'main'
    needs: [aws-cli, create-snapshot]
    name: Restore from blue
    runs-on: ubuntu-latest
    steps:
    - name: Restoring from blue
      run: | 
        aws rds db-snapshot-completed --db-snapshot-identifier ${{ needs.create-snapshot.outputs.snapshotIdentifier }}
        aws rds restore-db-instance-from-db-snapshot --db-instance-identifier green-db --db-snapshot-identifier ${{needs.create-snapshot.outputs.snapshotIdentifier}}
        echo "Testing outputs in resote job: ${{ needs.create-snapshot.snapshotIdentifier }}"
