name: Upload to S3
on: 
  push:
    branches:
    - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: S3 Upload Action
    - uses: hkusu/s3-upload-action@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-bucket: ${{ secrets.AWS_BUCKET }}
        file-path: './main.tf'