# Get Latest Tag name
#       |

# Check what branch the tag was on
#         |
# If tagged with wrong branch: error out 
# Else: refresh autoscale
# Then: Update last working commit on param store
# If tests failed: pull last working tag from param store and call workflow again with that commit

name: Get Branch of Tag
on:
  workflow_call:
  push:
    tags:
      - 'v*.*.*'
jobs:
# Get the latest Tag's branch and store into variable 
  getTB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Tag Name example
        id: get_tag
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.head_ref }}"
      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -l --contains ${{ github.ref_name }})
          echo "Branch is $raw."
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw}
          echo "Branch is $branch"

# Depending on what branch do an autoscale refresh to that environment
# If brannch = stage
  # Refresh to stage environment
# If branch = develop
  # Refresh to Develop
# If branch = main
  # Refresh to Production  


# If tests are a success - update last working commit on param store


# Else
  # Grab the latest commit from param store
  # Call workflow again
  # Refresh with this last working commit