
name: run_test
on:
  push:
    branches:
      - main
      - feature1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Main Branch
        if: github.ref == 'refs/heads/main'
        env:
          workingDirectory: ./environments/prod
      - name: Feature Branch
        if: github.ref == 'refs/heads/feature1'
        env:
          workingDirectory: ./environments/stage
        
      - name: Echo
        run: |
          echo ${{env.workingDirectory}}
          echo "test"
