name: ASG LoadBalancer
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  aws-cli: #Installing the AWS CLI on the runner, needed for the autoscaling cli commands. 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.7'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install awscli
  
  deploy-dev:
    needs:
      - aws-cli
    runs-on: ubuntu-latest
    env:
      ASGLB: ""
    steps:
      - name: Update Env Variable
        run: |
          CHCK=$(aws autoscaling describe-load-balancer-target-groups --auto-scaling-group-name testASGA --query 'LoadBalancerTargetGroups[0].LoadBalancerTargetGroupARN' --output text)
          echo "$CHCK"
          echo "ASGLB=$CHCK" >> $GITHUB_ENV
          echo " Env: ${{env.ASGLB}}"

      - name: Attach ASG B to TG
        run: aws autoscaling attach-load-balancer-target-groups --auto-scaling-group-name testASGB --target-group-arns arn:aws:elasticloadbalancing:us-west-1:070431401263:targetgroup/testTGA/d202852376dea472

      - name: Dettach ASG A
        run: aws autoscaling detach-load-balancer-target-groups --auto-scaling-group-name testASGA --target-group-arns arn:aws:elasticloadbalancing:us-west-1:070431401263:targetgroup/testTGA/d202852376dea472

      - name: Run smoke tests
        if: contains(github.event.head_commit.message, 'smoke_test')
        run: |
            echo 'Running smoke tests!'
            cd test

  rollback-job:
    needs:
      - aws-cli
      - deploy-dev
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Attach ASG A to TG
        run: aws autoscaling attach-load-balancer-target-groups --auto-scaling-group-name testASGA --target-group-arns arn:aws:elasticloadbalancing:us-west-1:070431401263:targetgroup/testTGA/d202852376dea472

      - name: Detttach ASG B
        run: aws autoscaling detach-load-balancer-target-groups --auto-scaling-group-name testASGB --target-group-arns arn:aws:elasticloadbalancing:us-west-1:070431401263:targetgroup/testTGA/d202852376dea472

      - name: Scale Down ASG B
        run: echo "Scaling Down....."