name: Deploy New Code 
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-west-1"


jobs:

# only runs additional steps if there is no other instance of `my-workflow.yml` currently runningsss
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Debug output
  #       run: |
  #         echo "${{ github.ref_name }}"
  #         echo "${{ github.event.after }}"
  #         echo "${{ github.event.before }}"
  #         echo "${{ github.event.branch }}"
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  wait-for-queued-workflow:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    name: workflow-last
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-queue@v1
        with:
          timeout: 24000000


  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - wait-for-queued-workflow
    steps:
      - name: Job One
        run: |
          echo "Testing and Deploying"
          exit 1

  # timer-wait-two:
  #   needssss:
  #     - deploy-dev
  #   if: success()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Wait 1 minutes for attachment to complete
  #       uses: jakejarvis/wait-action@master
  #       with:
  #         time: '1m'
  #     - name: Fail
  
  rollback-failure:
    runs-on: ubuntu-latest
    needs:
      - deploy-dev
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           set-safe-directory: true
           ref: ${{ github.ref_name }}
           fetch-depth: 0
      - name: Debug Workspace Contents
        run: |
          ls -la /rayala3314/aws-autoscale
      - name: Rolls back to a certain version
        uses: fivebluepetals/rollback-action@v1.0
        with:
          branch: ${{ github.ref_name }}
          revision: ${{ github.event.before }}
