
name: run_test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - main
env:
  GITHUB_CONTEXT: ${{ github.event.pull_request.draft}}
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo
        run: |
          echo "First YAML File"
          echo "$GITHUB_CONTEXT"
          echo "test"
          echo "Testing"
          echo "testing after"
      - name: Echo 2
        run: echo "Made it to second echo"
