
name: run_test
on:
  push:
    branches:
      - main
      - feature1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Branch Check
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=workingDirectory::./environments/prod"
          elif [ "${{ github.ref }}" = "refs/heads/feature1" ]; then
            echo "::set-output name=workingDirectory::./environments/stage"
          fi       
        
      - name: Echo
        run: |
          echo ${{ steps.branch_check.outputs.workingDirectory }}
          echo "test"
          
          
        
    outputs:
      workingDirectory: ${{ steps.branch_check.outputs.workingDirectory }}
